# snakemake -s mtImpute.smk --configfile mtImpute_config.yaml
## Config file for setting options in the mtImpute snakemake pipeline

## SAMPLE: File name of plink files
## DATAIN: File path to plink files
## DATAOUT: File path to write files out to
## REFDATA: File path to location of reference panel

SAMPLE: 'ExampleSamplePanel'
DATAIN: 'example/SamplePanel'
DATAOUT: "example/imputed"
REFDATA: "example/ReferencePanel"
INFOCUT: 0
ITER: 2
BURNIN: 1
KHAP: 1000

## Uncommenting below will use the full reference panel
#REFDATA: "ReferencePanel"
