# snakemake -j 1 --use-conda
## Config file for setting options in the mtImpute snakemake pipeline

## SAMPLE: File name of plink files
## DATAIN: File path to plink files
## DATAOUT: File path to write files out to
## REFAF: Reference Panel allele frequency cutoff [0.01, 0.005, 0.001, example]

SAMPLE: 'example'
DATAIN: 'resources/example'
DATAOUT: "results"
REFAF: 'example'
INFOCUT: 0
ITER: 2
BURNIN: 1
KHAP: 1000
